events {}

http {
    upstream api {
        server api:3000;
    }

    upstream game_1 {
        server game-1:3001;
    }

    upstream game_2 {
        server game-2:3001;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /game/game-1 {
            proxy_pass http://game_1/game/game-1;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /game/game-2 {
            proxy_pass http://game_2/game/game-2;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /health {
            default_type application/json;
            return 200 '{"status":"ok","service":"proxy"}';
        }
    }
}